---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hkarabakla/spring-cloud-config-files.git
          search-paths:
          - 'station*'
          #username: username
          #password: password